# Generated by Django 5.2.12 on 2026-03-23 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('CUS_ID', models.AutoField(primary_key=True, serialize=False)),
                ('CUSName', models.CharField(max_length=100)),
                ('CUSPhone', models.CharField(max_length=10)),
                ('CUSLine', models.CharField(blank=True, max_length=50, null=True)),
                ('CUSAddress', models.CharField(blank=True, max_length=255, null=True)),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('EMP_ID', models.AutoField(primary_key=True, serialize=False)),
                ('EMPName', models.CharField(max_length=100)),
                ('EMPAddress', models.CharField(blank=True, max_length=255, null=True)),
                ('EMPPhone', models.CharField(max_length=10)),
                ('EMP_Username', models.CharField(max_length=50, unique=True)),
                ('EMP_Password', models.CharField(max_length=255)),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('Role_ID', models.AutoField(primary_key=True, serialize=False)),
                ('RoleName', models.CharField(max_length=50)),
                ('Description', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('Service_ID', models.AutoField(primary_key=True, serialize=False)),
                ('ServiceType', models.CharField(max_length=100)),
                ('FabricType', models.CharField(max_length=100)),
                ('PriceService', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('Order_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Order_Date', models.DateTimeField(auto_now_add=True)),
                ('Status', models.CharField(max_length=50)),
                ('Totalprice', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('Note', models.CharField(blank=True, max_length=255, null=True)),
                ('CUS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.customer')),
                ('EMP', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('Payment_ID', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Payment_Date', models.DateTimeField(auto_now_add=True)),
                ('Payment_Method', models.CharField(max_length=50)),
                ('Payment_Status', models.CharField(max_length=50)),
                ('Order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.order')),
            ],
        ),
        migrations.CreateModel(
            name='Process_Tracking',
            fields=[
                ('Process_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Step', models.CharField(max_length=50)),
                ('Status', models.CharField(max_length=50)),
                ('Updated_at', models.DateTimeField(auto_now=True)),
                ('EMP', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.employee')),
                ('Order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.order')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='Role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.role'),
        ),
        migrations.CreateModel(
            name='Order_Item',
            fields=[
                ('Item_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Quantity', models.IntegerField(default=1)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.order')),
                ('Service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.service')),
            ],
        ),
    ]
