# Generated by Django 5.2.12 on 2026-03-24 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_item',
            name='Unit',
            field=models.CharField(default='ชิ้น', max_length=50),
        ),
    ]
