# Generated by Django 5.2.12 on 2026-03-25 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_order_item_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_item',
            name='Item_Status',
            field=models.CharField(default='รอดำเนินการ', max_length=50),
        ),
    ]
