# Generated by Django 5.2.12 on 2026-03-25 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_order_item_item_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process_tracking',
            name='Step',
            field=models.CharField(max_length=255),
        ),
    ]
