# Generated by Django 5.2.12 on 2026-03-26 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_process_tracking_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='Unit',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='หน่วย'),
        ),
    ]
