# Generated by Django 5.2.12 on 2026-03-26 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_service_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='EMP_Password',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='EMP_Username',
        ),
    ]
