# Generated by Django 5.2.12 on 2026-03-26 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_employee_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='Permissions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
